# Generated by Django 6.0.1 on 2026-01-09 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dilivery_days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('wallet', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_count', models.IntegerField(default=0)),
                ('working_status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Dilivery_addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('addresses_name', models.CharField(max_length=200)),
                ('langtude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dilivery.delivery')),
            ],
        ),
        migrations.CreateModel(
            name='Dilivery_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('group_id', models.CharField(max_length=100)),
                ('group_name', models.CharField(max_length=100)),
                ('dilivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dilivery.delivery')),
            ],
        ),
        migrations.CreateModel(
            name='Dilivery_group_topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('topic_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('topic_id', models.CharField(max_length=100)),
                ('dilivery_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dilivery.dilivery_group')),
            ],
        ),
        migrations.CreateModel(
            name='Dilivery_wallet_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('amount_cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_cart', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_taken', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dilivery.delivery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Dilivery_workdays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_time', models.CharField(max_length=100)),
                ('delivery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dilivery.delivery')),
                ('work_day', models.ManyToManyField(to='dilivery.dilivery_days')),
            ],
        ),
    ]
