# Generated by Django 6.0.1 on 2026-01-09 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('unique_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('langitude', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('wallet', models.CharField(max_length=255)),
                ('total_get_products_count', models.IntegerField()),
                ('stock', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('unique_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name_uz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_uzkr', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('unique_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name_uz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_uzkr', models.CharField(max_length=255)),
                ('stock_in_warehouse', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('input_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_kombo', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller.category')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Kombo_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField()),
                ('kombo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller.product')),
                ('product_id', models.ManyToManyField(blank=True, related_name='included_in_kombo', to='seller.product')),
            ],
        ),
        migrations.CreateModel(
            name='Seller_wallet_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField()),
                ('is_take', models.BooleanField(default=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller.seller')),
            ],
        ),
    ]
