# Generated by Django 6.0.1 on 2026-01-09 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='warehouse',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('lanitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('total_products', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='warehouse_group',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('group_name', models.CharField(max_length=255)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='warehouse_group_topic',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_id', models.IntegerField()),
                ('topic_name', models.CharField(max_length=255)),
                ('messeage_id', models.IntegerField()),
                ('warehouse_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse_group')),
            ],
        ),
    ]
