# Generated by Django 6.0.1 on 2026-01-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('unique_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telegram', models.CharField(max_length=255)),
                ('step', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=20)),
            ],
        ),
    ]
